### ISSUE TITLE
WOOOOW WELCOME BACK SIR!!

### ISSUE THREAD

**Issue by myweorld** [JaraLowell/NodeJSPacket#2]
nice to see you here ^^

**Comment by JaraLowell** [comment]
This is not quiet a Agar type of thing tough lol , this more for them ham people out there; well when the thing is finished. Getting there; adding and fixing things as we go

**Comment by myweorld** [comment]
You can overcome anything ^^

**Comment by myweorld** [comment]
Where can I reach you? I can reach you directly from here, but I would like to discuss the issue privately rather than here. If you don't mind, can you add me on discord? 

dc username: non_zerosumgame

**Comment by agarian-2** [comment]
Hello there. I found you back on ogar.mivabe.nl/master whilst having a nostalgia trip. You still have a server up to this day which is insane lol

**Comment by agarian-2** [comment]
I figured I would hop on the "long time no see" train.

**Comment by JaraLowell** [comment]
Yah that server still is ,running lol; no even know if people still use it lol; jaral#5425 or now jaralowell on discord tough granted not on 24/7

**Comment by agarian-2** [comment]
Yeah I played it for a bit lol, pretty empty though could use some more bots. Also, your Discord says it's not accepting friend requests ¯\_(ツ)_/¯

**Comment by JaraLowell** [comment]
Ah yah,. forgot that be still one, need find where again lol; was turned on due some physing bots that tough i was a catch... lol

**Comment by agarian-2** [comment]
Damn, Discord being Discord I suppose lol
